(cl:in-package roboclaw-msg)
(cl:export '(LEFT_DUTY_SP-VAL
          LEFT_DUTY_SP
          LEFT_DUTY-VAL
          LEFT_DUTY
          RIGHT_DUTY_SP-VAL
          RIGHT_DUTY_SP
          RIGHT_DUTY-VAL
          RIGHT_DUTY
          LEFT_QPPS_SP-VAL
          LEFT_QPPS_SP
          LEFT_QPPS-VAL
          LEFT_QPPS
          RIGHT_QPPS_SP-VAL
          RIGHT_QPPS_SP
          RIGHT_QPPS-VAL
          RIGHT_QPPS
          LEFT_SP-VAL
          LEFT_SP
          LEFT-VAL
          LEFT
          RIGHT_SP-VAL
          RIGHT_SP
          RIGHT-VAL
          RIGHT
          V_SP-VAL
          V_SP
          V-VAL
          V
          W_SP-VAL
          W_SP
          W-VAL
          W
          LEFT_PID_PE-VAL
          LEFT_PID_PE
          LEFT_PID_IE-VAL
          LEFT_PID_IE
          LEFT_PID_DE-VAL
          LEFT_PID_DE
          RIGHT_PID_PE-VAL
          RIGHT_PID_PE
          RIGHT_PID_IE-VAL
          RIGHT_PID_IE
          RIGHT_PID_DE-VAL
          RIGHT_PID_DE
))