// Generated by gencpp from file ite_info/orienteeringResponse.msg
// DO NOT EDIT!


#ifndef ITE_INFO_MESSAGE_ORIENTEERINGRESPONSE_H
#define ITE_INFO_MESSAGE_ORIENTEERINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>

namespace ite_info
{
template <class ContainerAllocator>
struct orienteeringResponse_
{
  typedef orienteeringResponse_<ContainerAllocator> Type;

  orienteeringResponse_()
    : orienteering_path()  {
    }
  orienteeringResponse_(const ContainerAllocator& _alloc)
    : orienteering_path(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _orienteering_path_type;
  _orienteering_path_type orienteering_path;




  typedef boost::shared_ptr< ::ite_info::orienteeringResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ite_info::orienteeringResponse_<ContainerAllocator> const> ConstPtr;

}; // struct orienteeringResponse_

typedef ::ite_info::orienteeringResponse_<std::allocator<void> > orienteeringResponse;

typedef boost::shared_ptr< ::ite_info::orienteeringResponse > orienteeringResponsePtr;
typedef boost::shared_ptr< ::ite_info::orienteeringResponse const> orienteeringResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ite_info::orienteeringResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ite_info::orienteeringResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ite_info

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ite_info::orienteeringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ite_info::orienteeringResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ite_info::orienteeringResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ite_info::orienteeringResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ite_info::orienteeringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ite_info::orienteeringResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ite_info::orienteeringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ef6bc8aad31579b2bc360cf02783125";
  }

  static const char* value(const ::ite_info::orienteeringResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ef6bc8aad31579bULL;
  static const uint64_t static_value2 = 0x2bc360cf02783125ULL;
};

template<class ContainerAllocator>
struct DataType< ::ite_info::orienteeringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ite_info/orienteeringResponse";
  }

  static const char* value(const ::ite_info::orienteeringResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ite_info::orienteeringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseArray orienteering_path\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseArray\n\
# An array of poses with a header for global reference.\n\
\n\
Header header\n\
\n\
Pose[] poses\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::ite_info::orienteeringResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ite_info::orienteeringResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.orienteering_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct orienteeringResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ite_info::orienteeringResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ite_info::orienteeringResponse_<ContainerAllocator>& v)
  {
    s << indent << "orienteering_path: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.orienteering_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ITE_INFO_MESSAGE_ORIENTEERINGRESPONSE_H
