// Generated by gencpp from file ite_info/orienteeringRequest.msg
// DO NOT EDIT!


#ifndef ITE_INFO_MESSAGE_ORIENTEERINGREQUEST_H
#define ITE_INFO_MESSAGE_ORIENTEERINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/PoseArray.h>

namespace ite_info
{
template <class ContainerAllocator>
struct orienteeringRequest_
{
  typedef orienteeringRequest_<ContainerAllocator> Type;

  orienteeringRequest_()
    : source()
    , goal()
    , budget(0.0)
    , robotname()
    , input_graph()  {
    }
  orienteeringRequest_(const ContainerAllocator& _alloc)
    : source(_alloc)
    , goal(_alloc)
    , budget(0.0)
    , robotname(_alloc)
    , input_graph(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _source_type;
  _source_type source;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _goal_type;
  _goal_type goal;

   typedef double _budget_type;
  _budget_type budget;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robotname_type;
  _robotname_type robotname;

   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _input_graph_type;
  _input_graph_type input_graph;




  typedef boost::shared_ptr< ::ite_info::orienteeringRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ite_info::orienteeringRequest_<ContainerAllocator> const> ConstPtr;

}; // struct orienteeringRequest_

typedef ::ite_info::orienteeringRequest_<std::allocator<void> > orienteeringRequest;

typedef boost::shared_ptr< ::ite_info::orienteeringRequest > orienteeringRequestPtr;
typedef boost::shared_ptr< ::ite_info::orienteeringRequest const> orienteeringRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ite_info::orienteeringRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ite_info::orienteeringRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ite_info

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ite_info::orienteeringRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ite_info::orienteeringRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ite_info::orienteeringRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ite_info::orienteeringRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ite_info::orienteeringRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ite_info::orienteeringRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ite_info::orienteeringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "346aab253c796caa262c5de22e8b11a6";
  }

  static const char* value(const ::ite_info::orienteeringRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x346aab253c796caaULL;
  static const uint64_t static_value2 = 0x262c5de22e8b11a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::ite_info::orienteeringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ite_info/orienteeringRequest";
  }

  static const char* value(const ::ite_info::orienteeringRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ite_info::orienteeringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose source\n\
geometry_msgs/Pose goal\n\
float64 budget\n\
string robotname\n\
geometry_msgs/PoseArray input_graph\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseArray\n\
# An array of poses with a header for global reference.\n\
\n\
Header header\n\
\n\
Pose[] poses\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ite_info::orienteeringRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ite_info::orienteeringRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.source);
      stream.next(m.goal);
      stream.next(m.budget);
      stream.next(m.robotname);
      stream.next(m.input_graph);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct orienteeringRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ite_info::orienteeringRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ite_info::orienteeringRequest_<ContainerAllocator>& v)
  {
    s << indent << "source: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.source);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
    s << indent << "budget: ";
    Printer<double>::stream(s, indent + "  ", v.budget);
    s << indent << "robotname: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robotname);
    s << indent << "input_graph: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.input_graph);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ITE_INFO_MESSAGE_ORIENTEERINGREQUEST_H
