// Generated by gencpp from file ite_command/InfoPath.msg
// DO NOT EDIT!


#ifndef ITE_COMMAND_MESSAGE_INFOPATH_H
#define ITE_COMMAND_MESSAGE_INFOPATH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace ite_command
{
template <class ContainerAllocator>
struct InfoPath_
{
  typedef InfoPath_<ContainerAllocator> Type;

  InfoPath_()
    : poses()
    , info(0.0)
    , endpose_info(0.0)
    , time(0.0)  {
    }
  InfoPath_(const ContainerAllocator& _alloc)
    : poses(_alloc)
    , info(0.0)
    , endpose_info(0.0)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _poses_type;
  _poses_type poses;

   typedef double _info_type;
  _info_type info;

   typedef double _endpose_info_type;
  _endpose_info_type endpose_info;

   typedef double _time_type;
  _time_type time;




  typedef boost::shared_ptr< ::ite_command::InfoPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ite_command::InfoPath_<ContainerAllocator> const> ConstPtr;

}; // struct InfoPath_

typedef ::ite_command::InfoPath_<std::allocator<void> > InfoPath;

typedef boost::shared_ptr< ::ite_command::InfoPath > InfoPathPtr;
typedef boost::shared_ptr< ::ite_command::InfoPath const> InfoPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ite_command::InfoPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ite_command::InfoPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ite_command

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ite_trajopt': ['/home/aravind/catkin_ws_ite/src/ite_core/ite_trajopt/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ite_command': ['/home/aravind/catkin_ws_ite/src/ite_core/ite_command/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ite_command::InfoPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ite_command::InfoPath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ite_command::InfoPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ite_command::InfoPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ite_command::InfoPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ite_command::InfoPath_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ite_command::InfoPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87f95e8fc6023dcea58079693dd44681";
  }

  static const char* value(const ::ite_command::InfoPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87f95e8fc6023dceULL;
  static const uint64_t static_value2 = 0xa58079693dd44681ULL;
};

template<class ContainerAllocator>
struct DataType< ::ite_command::InfoPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ite_command/InfoPath";
  }

  static const char* value(const ::ite_command::InfoPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ite_command::InfoPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose[] poses\n\
float64 info # Information of path\n\
float64 endpose_info # Information at final pose\n\
float64 time # Time to execute path\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::ite_command::InfoPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ite_command::InfoPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poses);
      stream.next(m.info);
      stream.next(m.endpose_info);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InfoPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ite_command::InfoPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ite_command::InfoPath_<ContainerAllocator>& v)
  {
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
    s << indent << "info: ";
    Printer<double>::stream(s, indent + "  ", v.info);
    s << indent << "endpose_info: ";
    Printer<double>::stream(s, indent + "  ", v.endpose_info);
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ITE_COMMAND_MESSAGE_INFOPATH_H
