; Auto-generated. Do not edit!


(cl:in-package scarab_msgs-msg)


;//! \htmlinclude MoveResult.msg.html

(cl:defclass <MoveResult> (roslisp-msg-protocol:ros-message)
  ((final_status
    :reader final_status
    :initarg :final_status
    :type cl:fixnum
    :initform 0))
)

(cl:defclass MoveResult (<MoveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name scarab_msgs-msg:<MoveResult> is deprecated: use scarab_msgs-msg:MoveResult instead.")))

(cl:ensure-generic-function 'final_status-val :lambda-list '(m))
(cl:defmethod final_status-val ((m <MoveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader scarab_msgs-msg:final_status-val is deprecated.  Use scarab_msgs-msg:final_status instead.")
  (final_status m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<MoveResult>)))
    "Constants for message type '<MoveResult>"
  '((:FINISHED . 0)
    (:TIMEOUT . 1)
    (:STUCK . 2)
    (:NOTREADY . 3)
    (:UNREACHABLE . 4))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'MoveResult)))
    "Constants for message type 'MoveResult"
  '((:FINISHED . 0)
    (:TIMEOUT . 1)
    (:STUCK . 2)
    (:NOTREADY . 3)
    (:UNREACHABLE . 4))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveResult>) ostream)
  "Serializes a message object of type '<MoveResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'final_status)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveResult>) istream)
  "Deserializes a message object of type '<MoveResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'final_status)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveResult>)))
  "Returns string type for a message object of type '<MoveResult>"
  "scarab_msgs/MoveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveResult)))
  "Returns string type for a message object of type 'MoveResult"
  "scarab_msgs/MoveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveResult>)))
  "Returns md5sum for a message object of type '<MoveResult>"
  "79b09be8622e2706904a1b48e955dad6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveResult)))
  "Returns md5sum for a message object of type 'MoveResult"
  "79b09be8622e2706904a1b48e955dad6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveResult>)))
  "Returns full string definition for message of type '<MoveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 FINISHED=0      # Successfully reached goal~%uint8 TIMEOUT=1       # Took too long to reach goal~%uint8 STUCK=2         # Robot has not moved in a while~%uint8 NOTREADY=3      # Don't have all the data we need to move, check back soon!~%uint8 UNREACHABLE=4   # Goal is no longer reachable (e.g., due to map change)~%~%uint8 final_status    # Status of robot when action was ended~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveResult)))
  "Returns full string definition for message of type 'MoveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 FINISHED=0      # Successfully reached goal~%uint8 TIMEOUT=1       # Took too long to reach goal~%uint8 STUCK=2         # Robot has not moved in a while~%uint8 NOTREADY=3      # Don't have all the data we need to move, check back soon!~%uint8 UNREACHABLE=4   # Goal is no longer reachable (e.g., due to map change)~%~%uint8 final_status    # Status of robot when action was ended~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveResult
    (cl:cons ':final_status (final_status msg))
))
