// Generated by gencpp from file ite_command/TeamActions.msg
// DO NOT EDIT!


#ifndef ITE_COMMAND_MESSAGE_TEAMACTIONS_H
#define ITE_COMMAND_MESSAGE_TEAMACTIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ite_command/RobotActions.h>
#include <ite_command/RobotActions.h>

namespace ite_command
{
template <class ContainerAllocator>
struct TeamActions_
{
  typedef TeamActions_<ContainerAllocator> Type;

  TeamActions_()
    : header()
    , planner_type()
    , duration(0.0)
    , scarab()
    , quad()  {
    }
  TeamActions_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , planner_type(_alloc)
    , duration(0.0)
    , scarab(_alloc)
    , quad(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _planner_type_type;
  _planner_type_type planner_type;

   typedef double _duration_type;
  _duration_type duration;

   typedef  ::ite_command::RobotActions_<ContainerAllocator>  _scarab_type;
  _scarab_type scarab;

   typedef  ::ite_command::RobotActions_<ContainerAllocator>  _quad_type;
  _quad_type quad;




  typedef boost::shared_ptr< ::ite_command::TeamActions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ite_command::TeamActions_<ContainerAllocator> const> ConstPtr;

}; // struct TeamActions_

typedef ::ite_command::TeamActions_<std::allocator<void> > TeamActions;

typedef boost::shared_ptr< ::ite_command::TeamActions > TeamActionsPtr;
typedef boost::shared_ptr< ::ite_command::TeamActions const> TeamActionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ite_command::TeamActions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ite_command::TeamActions_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ite_command

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ite_trajopt': ['/home/aravind/catkin_ws_ite/src/ite_core/ite_trajopt/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ite_command': ['/home/aravind/catkin_ws_ite/src/ite_core/ite_command/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ite_command::TeamActions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ite_command::TeamActions_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ite_command::TeamActions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ite_command::TeamActions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ite_command::TeamActions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ite_command::TeamActions_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ite_command::TeamActions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2644f81083808082cfaa9c0d038a7ce";
  }

  static const char* value(const ::ite_command::TeamActions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa2644f8108380808ULL;
  static const uint64_t static_value2 = 0x2cfaa9c0d038a7ceULL;
};

template<class ContainerAllocator>
struct DataType< ::ite_command::TeamActions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ite_command/TeamActions";
  }

  static const char* value(const ::ite_command::TeamActions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ite_command::TeamActions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
string planner_type\n\
float64 duration # How long to plan (sec)\n\
\n\
RobotActions scarab\n\
RobotActions quad\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: ite_command/RobotActions\n\
std_msgs/String name\n\
geometry_msgs/PoseStamped pose # Robot's pose\n\
InfoPath[] paths\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: ite_command/InfoPath\n\
geometry_msgs/Pose[] poses\n\
float64 info # Information of path\n\
float64 endpose_info # Information at final pose\n\
float64 time # Time to execute path\n\
";
  }

  static const char* value(const ::ite_command::TeamActions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ite_command::TeamActions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.planner_type);
      stream.next(m.duration);
      stream.next(m.scarab);
      stream.next(m.quad);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TeamActions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ite_command::TeamActions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ite_command::TeamActions_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "planner_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.planner_type);
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
    s << indent << "scarab: ";
    s << std::endl;
    Printer< ::ite_command::RobotActions_<ContainerAllocator> >::stream(s, indent + "  ", v.scarab);
    s << indent << "quad: ";
    s << std::endl;
    Printer< ::ite_command::RobotActions_<ContainerAllocator> >::stream(s, indent + "  ", v.quad);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ITE_COMMAND_MESSAGE_TEAMACTIONS_H
