# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from laser_simulator/ScanPair.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg
import sensor_msgs.msg

class ScanPair(genpy.Message):
  _md5sum = "8b8f9cfc12d41180f8cbbd1515a00b5e"
  _type = "laser_simulator/ScanPair"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """sensor_msgs/LaserScan scan1 
sensor_msgs/LaserScan scan2
geometry_msgs/Pose pose1
geometry_msgs/Pose pose2
geometry_msgs/Transform transform # Transformation from scan1 to scan2


================================================================================
MSG: sensor_msgs/LaserScan
# Single scan from a planar laser range-finder
#
# If you have another ranging device with different behavior (e.g. a sonar
# array), please find or create a different message, since applications
# will make fairly laser-specific assumptions about this data

Header header            # timestamp in the header is the acquisition time of 
                         # the first ray in the scan.
                         #
                         # in frame frame_id, angles are measured around 
                         # the positive Z axis (counterclockwise, if Z is up)
                         # with zero angle being forward along the x axis
                         
float32 angle_min        # start angle of the scan [rad]
float32 angle_max        # end angle of the scan [rad]
float32 angle_increment  # angular distance between measurements [rad]

float32 time_increment   # time between measurements [seconds] - if your scanner
                         # is moving, this will be used in interpolating position
                         # of 3d points
float32 scan_time        # time between scans [seconds]

float32 range_min        # minimum range value [m]
float32 range_max        # maximum range value [m]

float32[] ranges         # range data [m] (Note: values < range_min or > range_max should be discarded)
float32[] intensities    # intensity data [device-specific units].  If your
                         # device does not provide intensities, please leave
                         # the array empty.

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Transform
# This represents the transform between two coordinate frames in free space.

Vector3 translation
Quaternion rotation

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['scan1','scan2','pose1','pose2','transform']
  _slot_types = ['sensor_msgs/LaserScan','sensor_msgs/LaserScan','geometry_msgs/Pose','geometry_msgs/Pose','geometry_msgs/Transform']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       scan1,scan2,pose1,pose2,transform

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ScanPair, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.scan1 is None:
        self.scan1 = sensor_msgs.msg.LaserScan()
      if self.scan2 is None:
        self.scan2 = sensor_msgs.msg.LaserScan()
      if self.pose1 is None:
        self.pose1 = geometry_msgs.msg.Pose()
      if self.pose2 is None:
        self.pose2 = geometry_msgs.msg.Pose()
      if self.transform is None:
        self.transform = geometry_msgs.msg.Transform()
    else:
      self.scan1 = sensor_msgs.msg.LaserScan()
      self.scan2 = sensor_msgs.msg.LaserScan()
      self.pose1 = geometry_msgs.msg.Pose()
      self.pose2 = geometry_msgs.msg.Pose()
      self.transform = geometry_msgs.msg.Transform()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.scan1.header.seq, _x.scan1.header.stamp.secs, _x.scan1.header.stamp.nsecs))
      _x = self.scan1.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7f.pack(_x.scan1.angle_min, _x.scan1.angle_max, _x.scan1.angle_increment, _x.scan1.time_increment, _x.scan1.scan_time, _x.scan1.range_min, _x.scan1.range_max))
      length = len(self.scan1.ranges)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.scan1.ranges))
      length = len(self.scan1.intensities)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.scan1.intensities))
      _x = self
      buff.write(_struct_3I.pack(_x.scan2.header.seq, _x.scan2.header.stamp.secs, _x.scan2.header.stamp.nsecs))
      _x = self.scan2.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7f.pack(_x.scan2.angle_min, _x.scan2.angle_max, _x.scan2.angle_increment, _x.scan2.time_increment, _x.scan2.scan_time, _x.scan2.range_min, _x.scan2.range_max))
      length = len(self.scan2.ranges)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.scan2.ranges))
      length = len(self.scan2.intensities)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.scan2.intensities))
      _x = self
      buff.write(_struct_21d.pack(_x.pose1.position.x, _x.pose1.position.y, _x.pose1.position.z, _x.pose1.orientation.x, _x.pose1.orientation.y, _x.pose1.orientation.z, _x.pose1.orientation.w, _x.pose2.position.x, _x.pose2.position.y, _x.pose2.position.z, _x.pose2.orientation.x, _x.pose2.orientation.y, _x.pose2.orientation.z, _x.pose2.orientation.w, _x.transform.translation.x, _x.transform.translation.y, _x.transform.translation.z, _x.transform.rotation.x, _x.transform.rotation.y, _x.transform.rotation.z, _x.transform.rotation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.scan1 is None:
        self.scan1 = sensor_msgs.msg.LaserScan()
      if self.scan2 is None:
        self.scan2 = sensor_msgs.msg.LaserScan()
      if self.pose1 is None:
        self.pose1 = geometry_msgs.msg.Pose()
      if self.pose2 is None:
        self.pose2 = geometry_msgs.msg.Pose()
      if self.transform is None:
        self.transform = geometry_msgs.msg.Transform()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.scan1.header.seq, _x.scan1.header.stamp.secs, _x.scan1.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.scan1.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.scan1.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.scan1.angle_min, _x.scan1.angle_max, _x.scan1.angle_increment, _x.scan1.time_increment, _x.scan1.scan_time, _x.scan1.range_min, _x.scan1.range_max,) = _struct_7f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.scan1.ranges = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.scan1.intensities = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 12
      (_x.scan2.header.seq, _x.scan2.header.stamp.secs, _x.scan2.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.scan2.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.scan2.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.scan2.angle_min, _x.scan2.angle_max, _x.scan2.angle_increment, _x.scan2.time_increment, _x.scan2.scan_time, _x.scan2.range_min, _x.scan2.range_max,) = _struct_7f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.scan2.ranges = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.scan2.intensities = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 168
      (_x.pose1.position.x, _x.pose1.position.y, _x.pose1.position.z, _x.pose1.orientation.x, _x.pose1.orientation.y, _x.pose1.orientation.z, _x.pose1.orientation.w, _x.pose2.position.x, _x.pose2.position.y, _x.pose2.position.z, _x.pose2.orientation.x, _x.pose2.orientation.y, _x.pose2.orientation.z, _x.pose2.orientation.w, _x.transform.translation.x, _x.transform.translation.y, _x.transform.translation.z, _x.transform.rotation.x, _x.transform.rotation.y, _x.transform.rotation.z, _x.transform.rotation.w,) = _struct_21d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.scan1.header.seq, _x.scan1.header.stamp.secs, _x.scan1.header.stamp.nsecs))
      _x = self.scan1.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7f.pack(_x.scan1.angle_min, _x.scan1.angle_max, _x.scan1.angle_increment, _x.scan1.time_increment, _x.scan1.scan_time, _x.scan1.range_min, _x.scan1.range_max))
      length = len(self.scan1.ranges)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.scan1.ranges.tostring())
      length = len(self.scan1.intensities)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.scan1.intensities.tostring())
      _x = self
      buff.write(_struct_3I.pack(_x.scan2.header.seq, _x.scan2.header.stamp.secs, _x.scan2.header.stamp.nsecs))
      _x = self.scan2.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7f.pack(_x.scan2.angle_min, _x.scan2.angle_max, _x.scan2.angle_increment, _x.scan2.time_increment, _x.scan2.scan_time, _x.scan2.range_min, _x.scan2.range_max))
      length = len(self.scan2.ranges)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.scan2.ranges.tostring())
      length = len(self.scan2.intensities)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.scan2.intensities.tostring())
      _x = self
      buff.write(_struct_21d.pack(_x.pose1.position.x, _x.pose1.position.y, _x.pose1.position.z, _x.pose1.orientation.x, _x.pose1.orientation.y, _x.pose1.orientation.z, _x.pose1.orientation.w, _x.pose2.position.x, _x.pose2.position.y, _x.pose2.position.z, _x.pose2.orientation.x, _x.pose2.orientation.y, _x.pose2.orientation.z, _x.pose2.orientation.w, _x.transform.translation.x, _x.transform.translation.y, _x.transform.translation.z, _x.transform.rotation.x, _x.transform.rotation.y, _x.transform.rotation.z, _x.transform.rotation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.scan1 is None:
        self.scan1 = sensor_msgs.msg.LaserScan()
      if self.scan2 is None:
        self.scan2 = sensor_msgs.msg.LaserScan()
      if self.pose1 is None:
        self.pose1 = geometry_msgs.msg.Pose()
      if self.pose2 is None:
        self.pose2 = geometry_msgs.msg.Pose()
      if self.transform is None:
        self.transform = geometry_msgs.msg.Transform()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.scan1.header.seq, _x.scan1.header.stamp.secs, _x.scan1.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.scan1.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.scan1.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.scan1.angle_min, _x.scan1.angle_max, _x.scan1.angle_increment, _x.scan1.time_increment, _x.scan1.scan_time, _x.scan1.range_min, _x.scan1.range_max,) = _struct_7f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.scan1.ranges = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.scan1.intensities = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 12
      (_x.scan2.header.seq, _x.scan2.header.stamp.secs, _x.scan2.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.scan2.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.scan2.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.scan2.angle_min, _x.scan2.angle_max, _x.scan2.angle_increment, _x.scan2.time_increment, _x.scan2.scan_time, _x.scan2.range_min, _x.scan2.range_max,) = _struct_7f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.scan2.ranges = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.scan2.intensities = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 168
      (_x.pose1.position.x, _x.pose1.position.y, _x.pose1.position.z, _x.pose1.orientation.x, _x.pose1.orientation.y, _x.pose1.orientation.z, _x.pose1.orientation.w, _x.pose2.position.x, _x.pose2.position.y, _x.pose2.position.z, _x.pose2.orientation.x, _x.pose2.orientation.y, _x.pose2.orientation.z, _x.pose2.orientation.w, _x.transform.translation.x, _x.transform.translation.y, _x.transform.translation.z, _x.transform.rotation.x, _x.transform.rotation.y, _x.transform.rotation.z, _x.transform.rotation.w,) = _struct_21d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_7f = struct.Struct("<7f")
_struct_3I = struct.Struct("<3I")
_struct_21d = struct.Struct("<21d")
