//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the roboclaw package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __roboclaw__ROBOCLAWCONFIG_H__
#define __roboclaw__ROBOCLAWCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace roboclaw
{
  class RoboclawConfigStatics;
  
  class RoboclawConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(RoboclawConfig &config, const RoboclawConfig &max, const RoboclawConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const RoboclawConfig &config1, const RoboclawConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, RoboclawConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const RoboclawConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, RoboclawConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const RoboclawConfig &config) const = 0;
      virtual void getValue(const RoboclawConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T RoboclawConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (RoboclawConfig::* field);

      virtual void clamp(RoboclawConfig &config, const RoboclawConfig &max, const RoboclawConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const RoboclawConfig &config1, const RoboclawConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, RoboclawConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const RoboclawConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, RoboclawConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const RoboclawConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const RoboclawConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, RoboclawConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, RoboclawConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<RoboclawConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(RoboclawConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("pid_p"==(*_i)->name){pid_p = boost::any_cast<double>(val);}
        if("pid_i"==(*_i)->name){pid_i = boost::any_cast<double>(val);}
        if("pid_d"==(*_i)->name){pid_d = boost::any_cast<double>(val);}
        if("pid_iclamp"==(*_i)->name){pid_iclamp = boost::any_cast<double>(val);}
        if("accel_max"==(*_i)->name){accel_max = boost::any_cast<double>(val);}
        if("max_wheel_vel"==(*_i)->name){max_wheel_vel = boost::any_cast<double>(val);}
        if("min_wheel_vel"==(*_i)->name){min_wheel_vel = boost::any_cast<double>(val);}
        if("wheel_diam"==(*_i)->name){wheel_diam = boost::any_cast<double>(val);}
        if("quad_pulse_per_motor_rev"==(*_i)->name){quad_pulse_per_motor_rev = boost::any_cast<int>(val);}
        if("motor_to_wheel_ratio"==(*_i)->name){motor_to_wheel_ratio = boost::any_cast<double>(val);}
        if("axle_width"==(*_i)->name){axle_width = boost::any_cast<double>(val);}
        if("freq"==(*_i)->name){freq = boost::any_cast<double>(val);}
        if("odom_frame"==(*_i)->name){odom_frame = boost::any_cast<std::string>(val);}
        if("base_frame"==(*_i)->name){base_frame = boost::any_cast<std::string>(val);}
        if("pid_error_reset_v_step_threshold"==(*_i)->name){pid_error_reset_v_step_threshold = boost::any_cast<double>(val);}
        if("pid_error_reset_w_step_threshold"==(*_i)->name){pid_error_reset_w_step_threshold = boost::any_cast<double>(val);}
        if("pid_error_reset_min_v"==(*_i)->name){pid_error_reset_min_v = boost::any_cast<double>(val);}
        if("pid_error_reset_min_w"==(*_i)->name){pid_error_reset_min_w = boost::any_cast<double>(val);}
      }
    }

    double pid_p;
double pid_i;
double pid_d;
double pid_iclamp;
double accel_max;
double max_wheel_vel;
double min_wheel_vel;
double wheel_diam;
int quad_pulse_per_motor_rev;
double motor_to_wheel_ratio;
double axle_width;
double freq;
std::string odom_frame;
std::string base_frame;
double pid_error_reset_v_step_threshold;
double pid_error_reset_w_step_threshold;
double pid_error_reset_min_v;
double pid_error_reset_min_w;

    bool state;
    std::string name;

    
}groups;



//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pid_p;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pid_i;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pid_d;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pid_iclamp;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_max;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_wheel_vel;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_wheel_vel;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wheel_diam;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int quad_pulse_per_motor_rev;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double motor_to_wheel_ratio;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double axle_width;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double freq;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string odom_frame;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string base_frame;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pid_error_reset_v_step_threshold;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pid_error_reset_w_step_threshold;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pid_error_reset_min_v;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pid_error_reset_min_w;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("RoboclawConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const RoboclawConfig &__max__ = __getMax__();
      const RoboclawConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const RoboclawConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const RoboclawConfig &__getDefault__();
    static const RoboclawConfig &__getMax__();
    static const RoboclawConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const RoboclawConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void RoboclawConfig::ParamDescription<std::string>::clamp(RoboclawConfig &config, const RoboclawConfig &max, const RoboclawConfig &min) const
  {
    return;
  }

  class RoboclawConfigStatics
  {
    friend class RoboclawConfig;
    
    RoboclawConfigStatics()
    {
RoboclawConfig::GroupDescription<RoboclawConfig::DEFAULT, RoboclawConfig> Default("Default", "", 0, 0, true, &RoboclawConfig::groups);
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pid_p = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pid_p = 50.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pid_p = 1.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("pid_p", "double", 0, "PID Proportional gain", "", &RoboclawConfig::pid_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("pid_p", "double", 0, "PID Proportional gain", "", &RoboclawConfig::pid_p)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pid_i = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pid_i = 50.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pid_i = 4.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("pid_i", "double", 0, "PID Integral gain", "", &RoboclawConfig::pid_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("pid_i", "double", 0, "PID Integral gain", "", &RoboclawConfig::pid_i)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pid_d = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pid_d = 50.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pid_d = 0.2;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("pid_d", "double", 0, "PID Derivative gain", "", &RoboclawConfig::pid_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("pid_d", "double", 0, "PID Derivative gain", "", &RoboclawConfig::pid_d)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pid_iclamp = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pid_iclamp = 1000.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pid_iclamp = 500.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("pid_iclamp", "double", 0, "Max I magnitude", "", &RoboclawConfig::pid_iclamp)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("pid_iclamp", "double", 0, "Max I magnitude", "", &RoboclawConfig::pid_iclamp)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_max = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_max = 2.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_max = 1.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("accel_max", "double", 0, "Maximum wheel acceleration (m/s^2)", "", &RoboclawConfig::accel_max)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("accel_max", "double", 0, "Maximum wheel acceleration (m/s^2)", "", &RoboclawConfig::accel_max)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_wheel_vel = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_wheel_vel = 1.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_wheel_vel = 0.8;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("max_wheel_vel", "double", 0, "Maximum individual wheel speed (m/s)", "", &RoboclawConfig::max_wheel_vel)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("max_wheel_vel", "double", 0, "Maximum individual wheel speed (m/s)", "", &RoboclawConfig::max_wheel_vel)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_wheel_vel = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_wheel_vel = 1.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_wheel_vel = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("min_wheel_vel", "double", 0, "Minimum individual wheel speed (m/s)", "", &RoboclawConfig::min_wheel_vel)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("min_wheel_vel", "double", 0, "Minimum individual wheel speed (m/s)", "", &RoboclawConfig::min_wheel_vel)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wheel_diam = 0.01;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wheel_diam = 0.5;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wheel_diam = 0.1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("wheel_diam", "double", 0, "Wheel diameter (m)", "", &RoboclawConfig::wheel_diam)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("wheel_diam", "double", 0, "Wheel diameter (m)", "", &RoboclawConfig::wheel_diam)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.quad_pulse_per_motor_rev = 0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.quad_pulse_per_motor_rev = 5000;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.quad_pulse_per_motor_rev = 2000;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<int>("quad_pulse_per_motor_rev", "int", 0, "Quad pulses / motor revolution", "", &RoboclawConfig::quad_pulse_per_motor_rev)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<int>("quad_pulse_per_motor_rev", "int", 0, "Quad pulses / motor revolution", "", &RoboclawConfig::quad_pulse_per_motor_rev)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.motor_to_wheel_ratio = 0.01;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.motor_to_wheel_ratio = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.motor_to_wheel_ratio = 38.35;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("motor_to_wheel_ratio", "double", 0, "Number of motor revolutions for one wheel revolution", "", &RoboclawConfig::motor_to_wheel_ratio)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("motor_to_wheel_ratio", "double", 0, "Number of motor revolutions for one wheel revolution", "", &RoboclawConfig::motor_to_wheel_ratio)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.axle_width = 0.01;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.axle_width = 0.4;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.axle_width = 0.255;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("axle_width", "double", 0, "Spacing between wheels (m)", "", &RoboclawConfig::axle_width)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("axle_width", "double", 0, "Spacing between wheels (m)", "", &RoboclawConfig::axle_width)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.freq = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.freq = 100.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.freq = 50.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("freq", "double", 0, "The update rate of odometry integration (Hz)", "", &RoboclawConfig::freq)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("freq", "double", 0, "The update rate of odometry integration (Hz)", "", &RoboclawConfig::freq)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.odom_frame = "";
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.odom_frame = "";
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.odom_frame = "odom_motor";
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<std::string>("odom_frame", "str", 0, "The odometry frame of the robot", "", &RoboclawConfig::odom_frame)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<std::string>("odom_frame", "str", 0, "The odometry frame of the robot", "", &RoboclawConfig::odom_frame)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.base_frame = "";
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.base_frame = "";
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.base_frame = "base_link";
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<std::string>("base_frame", "str", 0, "The local frame of the robot", "", &RoboclawConfig::base_frame)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<std::string>("base_frame", "str", 0, "The local frame of the robot", "", &RoboclawConfig::base_frame)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pid_error_reset_v_step_threshold = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pid_error_reset_v_step_threshold = 1.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pid_error_reset_v_step_threshold = 0.1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("pid_error_reset_v_step_threshold", "double", 0, "Min linear velocity change to reset PID errors (m/s)", "", &RoboclawConfig::pid_error_reset_v_step_threshold)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("pid_error_reset_v_step_threshold", "double", 0, "Min linear velocity change to reset PID errors (m/s)", "", &RoboclawConfig::pid_error_reset_v_step_threshold)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pid_error_reset_w_step_threshold = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pid_error_reset_w_step_threshold = 2.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pid_error_reset_w_step_threshold = 0.3;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("pid_error_reset_w_step_threshold", "double", 0, "Min angular velocity change to reset PID errors (rad/s)", "", &RoboclawConfig::pid_error_reset_w_step_threshold)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("pid_error_reset_w_step_threshold", "double", 0, "Min angular velocity change to reset PID errors (rad/s)", "", &RoboclawConfig::pid_error_reset_w_step_threshold)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pid_error_reset_min_v = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pid_error_reset_min_v = 0.1;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pid_error_reset_min_v = 0.01;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("pid_error_reset_min_v", "double", 0, "Min linear velocity to reset PID errors (m/s)", "", &RoboclawConfig::pid_error_reset_min_v)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("pid_error_reset_min_v", "double", 0, "Min linear velocity to reset PID errors (m/s)", "", &RoboclawConfig::pid_error_reset_min_v)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pid_error_reset_min_w = 0.0;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pid_error_reset_min_w = 0.2;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pid_error_reset_min_w = 0.01;
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("pid_error_reset_min_w", "double", 0, "Min angular velocity to reset PID errors (rad/s)", "", &RoboclawConfig::pid_error_reset_min_w)));
//#line 280 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RoboclawConfig::AbstractParamDescriptionConstPtr(new RoboclawConfig::ParamDescription<double>("pid_error_reset_min_w", "double", 0, "Min angular velocity to reset PID errors (rad/s)", "", &RoboclawConfig::pid_error_reset_min_w)));
//#line 235 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 235 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(RoboclawConfig::AbstractGroupDescriptionConstPtr(new RoboclawConfig::GroupDescription<RoboclawConfig::DEFAULT, RoboclawConfig>(Default)));
//#line 353 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<RoboclawConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<RoboclawConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<RoboclawConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    RoboclawConfig __max__;
    RoboclawConfig __min__;
    RoboclawConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const RoboclawConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static RoboclawConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &RoboclawConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const RoboclawConfig &RoboclawConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const RoboclawConfig &RoboclawConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const RoboclawConfig &RoboclawConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<RoboclawConfig::AbstractParamDescriptionConstPtr> &RoboclawConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<RoboclawConfig::AbstractGroupDescriptionConstPtr> &RoboclawConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const RoboclawConfigStatics *RoboclawConfig::__get_statics__()
  {
    const static RoboclawConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = RoboclawConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __ROBOCLAWRECONFIGURATOR_H__
